#spring setting
spring:
  application:
    name: Admin-Website
  profiles:
    active: test
#common setting
website:
  # 网站支持
  support:
    welcome-file: /index
#  session:
#    exclude-path: /rest/**
#    authentication: sso
#    exclude-path: /index, /login
#  security:
#    open-ddoc: true
#    ddos:
#      access-control-allow-origin: www.zzl.com
##    open-csrf: true
#    csrf:
#      verify-exclude-path: /index